//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reczna_Myjnia_Samochodowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public int ID_order { get; set; }
        public int ID_service { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
